### ISSUE TITLE
editor: cursor position is offset from editor position

### ISSUE THREAD

**Issue by slate0** [jfrohnhofen/metamaterial-mechanisms#3]
I can get this program working on several computers (it is amazing, thank you!).
However, on some computers (Windows 7 and 10) we are stuck with Firefox, and it appears that some setting is causing the mouse cursor to be offset on the y-axis from the editor's understanding of where the cursor is.

So for example, when I place an anchor, I move my cursor 2 inches below the target point where I want the anchor to appear.

Do you know what part of the source I might start looking at in order to try to debug this problem?

Thank you!

**Comment by jfrohnhofen** [comment]
I tried and failed to reproduce the issue with Firefox on macOS, since I don't have Windows available to me right now.
Does the problem occur with all interactions (in the main editor scene) or only when placing anchors? A good place to start looking might be in `tool.js` (especially here: https://github.com/jfrohnhofen/metamaterial-mechanisms/blob/master/editor/src/js/tools/tool.js#L82), since this is where the mouse handlers are managed and mouse coordinates are translated into viewport coordinates.

**Comment by slate0** [comment]
Hi, I am sorry.  The problem went away overnight.  Rays from the sun?  I will keep an eye on it to see if it comes back.  Thank you for your support and suggestions.  (At the time it was only with anchors or the force).  Thank you for pointing me to the right .js file, at leas I can learn from this!

**Comment by alexiiion** [comment]
It's late, but just for the reference of others: 
The cursor is offset if too many panels are open such that they don't fit onto the screen anymore. Current work-around: close one panel.
